docs/providers/dependency.rst

I just fixed a small typo in the documentation (which is great by the way).
Thanks

Fix small typo in documentation

---

MANIFEST.in

I have added the `tests` directory and the `tox.ini` in `MANIFEST.in` to be able to run the tests after installing the source via PyPi to check if the installation ran successfully.
Motivation: https://github.com/NixOS/nixpkgs/pull/45871#issuecomment-417854526

Adds tests in MANIFEST.in

---

src/dependency_injector/providers.c
src/dependency_injector/providers.pyx
tests/unit/providers/test_singletons_py2_py3.py

This aims to fix a bug with the `reset` method for ThreadLocalSingletons.
https://github.com/ets-labs/python-dependency-injector/issues/217

Bugfix thread local singleton reset

---

src/dependency_injector/providers.pyx

The `self.__storage` attribute may be overwritten by the `ThreadSafeSingleton.reset()` method and thus will return a None from the `_provide(...)` method.
Additionally, we should place a return statement inside the lock to prevent reading the shared variable. A more efficient solution is 'double-checked locking optimization.'

Fix race in ThreadSafeSingleton

---

examples/providers/singleton_scoped.py

Make example more realistic.  This would break if you're running flask with multiple threads.

Fix provider documentation

---

docs/providers/configuration.rst

the interpolation of the environment variables example in yaml is wrong, I have changed the example from {$ ENV_VAR} to $ {ENV_VAR}

Fix yaml configuration-envs-interpolation examples

---

examples/providers/factory_attribute_injections.py

Fixed typo in docs
Closes #499

Fixed a typo in Factory provider docs "service.add_attributes(clent=client)" #499

---

src/dependency_injector/wiring.py
tests/unit/samples/wiring/imports.py

Modify `InspectFilter._is_starlette_request_cls` by using a `_safe_is_subclass` method that returns `False` instead of raising a `TypeError`
closes #569

569 fix numpy typing wiring

---

docs/main/changelog.rst
docs/wiring.rst
src/dependency_injector/_cwiring.c
src/dependency_injector/_cwiring.pyx
src/dependency_injector/wiring.py
tests/unit/wiring/test_inject_and_wraps_decorator_py36.py
tests/unit/wiring/test_wiring_with_wraps_decorator_py36.py

(#454) (#597) Fix @inject + @wraps, refactor patched callables registry and injections storage principles 

---

docs/providers/custom.rst

Wasted a couple of hours because I forgot to pass `memo` when using `deepcopy` 😄 
Mentioning it explicitly like this will hopefully prevent this for other people in the future.

Explicitly mention the required usage of "memo"

---

setup.py

I got some problems when i tried to build the package on windows 11 with cp1251 encoding by default.
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 8667: character maps to <undefined>`

fixed bug in windows build with default charset

---

src/dependency_injector/wiring.py
tests/unit/samples/wiringstringids/resourceclosing.py
tests/unit/wiring/string_ids/test_main_py36.py

This attempts to fix Issue #633 by detecting `providers.Resource` that are dependencies of other injected dependencies.

Allow `Closing` to detect dependent resources

---

.github/workflows/tests-and-linters.yml
docs/providers/configuration.rst
examples/miniapps/fastapi-redis/fastapiredis/tests.py
examples/miniapps/fastapi-simple/tests.py
examples/miniapps/fastapi/giphynavigator/tests.py
examples/providers/configuration/configuration_pydantic.py
examples/providers/configuration/configuration_pydantic_init.py
pyproject.toml
src/dependency_injector/providers.pyx
tests/.configs/pytest.ini
tests/unit/providers/configuration/test_from_pydantic_py36.py
tests/unit/providers/configuration/test_pydantic_settings_in_init_py36.py
tests/unit/wiring/test_fastapi_py36.py
tox.ini

This PR supersede #803, #786, #785 (partially), #768 and fixes #755, #726.
Notable differences:
* Updated GHA pipeline to run tests against two versions of Pydantic.
* Better error messages depending on installed Pydantic version.
* Minor code de-duplication.
There is one necessary but unrelated commit to fix compatibility with httpx [v0.27.0](https://github.com/encode/httpx/blob/master/CHANGELOG.md#0270-21st-february-2024). Without this change tests are failing.

Yet another Pydantic 2 support

---

requirements-ext.txt
tests/typing/configuration.py
tests/unit/samples/wiringflask/web.py
tox.ini

Resolve Dependabot warnings.
Note: flask removed `_request_ctx_stack` and `_app_ctx_stack`, but test is still testing what it was supposed to test, since `request`, `current_app`, `session` and `g` are also `LocalProxy`.

Upgrade testing deps

---

src/dependency_injector/providers.pyx
tests/unit/providers/singleton/test_thread_local_singleton_py3.py

We use the dependency-injector a lot in our private project. Currently, when the configuration of the ThreadLocalSingleton is invalid (i.e. a constructor argument is forgotten), the library prints only this exception:
```
UnboundLocalError: local variable 'instance' referenced before assignment
```
This is really frustrating, because it provides no leads to the actual error. At the company, for last 7 months, we use a fork of this library, https://github.com/gortibaldik/dependency-injector-fg with a separate PyPI repo. However as we see that this project is again maintained, we would like to merge this small PR, which solves approx 50% of all of our problems with the library (the other 50% are issues with wiring which stem from our misunderstandings... :grinning: ).

:art: Raise exception instead of hiding it in finally

---

examples/miniapps/starlette-lifespan/README.rst
examples/miniapps/starlette-lifespan/example.py
examples/miniapps/starlette-lifespan/requirements.txt
src/dependency_injector/ext/starlette.py
tests/unit/ext/test_starlette.py

Starlette recently added cool new feature called [lifespan](https://www.starlette.io/lifespan/) in [v0.26.0](https://github.com/encode/starlette/releases/tag/0.26.0) and FastAPI [followed the suit](https://fastapi.tiangolo.com/advanced/events/#lifespan) in [v0.93.0](https://github.com/tiangolo/fastapi/releases/tag/0.93.0). This makes it possible to get rid of good chunk of initialization spaghetti in starlette-based apps (making container a single entry point in the application), + reduces amount of the pain in the ass scheduling background tasks in the event loop of the ASGI app.
<details>
<summary>Example</summary>
`myapp/container.py`
```python
from dependency_injector.containers import DeclarativeContainer
from dependency_injector.ext.starlette import Lifespan
from …
```

Add Starlette lifespan handler implementation

---

.github/workflows/publishing.yml

`actions/upload-artifact@v3` will be EOL-ed in [January 30, 2025](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#artifacts-v3-brownouts). Upgrade our publishing pipeline according to [official migration guidelines](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md). Changes are based on https://github.com/pypa/cibuildwheel/commit/2c4974286fe784b47c157b64a6c61a229b9935ee

Migrate CI pipeline to actions/upload-artifact@v4

---

docs/tutorials/cli.rst
examples/miniapps/movie-lister/movies/tests.py

**Link to the current version: _[tutorials/cli](https://python-dependency-injector.ets-labs.org/tutorials/cli.html#tests)_**
This pull request proposes the following changes:
- Added a new test fixture `finder_mock` for `examples/miniapps/movie-lister/movies/tests.py`.
- Updated the example in the documentation to reflect the use of the new fixture.
These changes allow for:
- Reduced code duplication.
- Updating the documentation makes it more relevant and informative for framework users.
Didn't notice any problems, just run `pytest movies/tests.py --cov=movies` and `pytest movies/tests.py` from `python-dependency-injector/examples/miniapps/movie-lister` directory.

[movie-lister] Added test fixture and updated documentation

---

.github/workflows/publishing.yml

ARM images are [now officially available for opensource repos](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/). Use these images instead of spinning up QEMU. This change will significantly improve our publishing pipeline times.
Also updated ubuntu image versions to match ones from `tests-and-linters.yml`.

Native GHA ARM runners

---

src/dependency_injector/providers.pyx
tests/unit/providers/coroutines/test_coroutine_py35.py

This improves Python 3.12+ support.
Background:
[@asyncio.coroutine](https://docs.python.org/3.10/library/asyncio-task.html#asyncio.coroutine) is no longer available since 3.11, [asyncio.iscoroutinefunction()](https://docs.python.org/3.10/library/asyncio-task.html#asyncio.iscoroutinefunction) was a helper function to detect generator-based coroutines, i.e. functions marked with `@asyncio.coroutine` decorator, which set `_is_coroutine` attribute. This implementation detail was historically abused to mark sync functions returning awaitables.
Since 3.12, [inspect.markcoroutinefunction()](https://docs.python.org/3.12/library/inspect.html#inspect.markcoroutinefunction) is a preferred way to mark sync functions returning awaitables. It is intended to be used with …

Add support for inspect.iscoroutinefunction() for Coroutine provider

---

docs/providers/configuration.rst
src/dependency_injector/providers.pyi
src/dependency_injector/providers.pyx
tests/unit/providers/configuration/test_from_ini_with_env_py2_py3.py
tests/unit/providers/configuration/test_from_json_with_env_py2_py3.py
tests/unit/providers/configuration/test_from_yaml_with_env_py2_py3.py

Env var interpolation for config files were introduced in #467, but no option to disable this feature were introduced. This PR fixes #857 by adding option to disable this functionality by handling `envs_required=None`. Minor refactoring to improve performance of used private methods (cdef-ify) + removing Python 2 legacy.

Add option to disable env var interpolation in configs

---

src/dependency_injector/wiring.py
tests/unit/samples/wiringstringids/resourceclosing.py

Fix infinite loop with Closing+ConfigurationOption

---

.github/workflows/tests-and-linters.yml
pyproject.toml
src/dependency_injector/providers.pyx
tests/unit/providers/resource/test_async_resource_py35.py
tox.ini

* GitHub Actions has [dropped support](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#ubuntu-20-image-is-closing-down) for Ubuntu 20.04, so we no longer able run test for legacy Python versions.
* Python 3.7 was EOL-ed for about 2 years by now.

Drop Python 3.7 support

---

requirements-dev.txt
setup.py

Also add initial support for ABI3 builds (Limited API).

Update Cython to v3.1

---

.github/workflows/publishing.yml
.github/workflows/tests-and-linters.yml
.gitignore
MANIFEST.in
pyproject.toml
requirements-dev.txt
setup.py
tox.ini

Fix some warnings, but more importantly - migrate to ABI3 wheels for CPython. This reduces build time from 1h+ to ~16m + 5x times size reduction (fixes #487).

Build improvements

---

src/dependency_injector/_cwiring.pyi
src/dependency_injector/_cwiring.pyx
src/dependency_injector/wiring.py
tests/unit/samples/wiring/asyncinjections.py
tests/unit/wiring/provider_ids/test_async_injections_py36.py

Fixes #603 and #745.
`_cwiring.pyx` got major overhaul, but otherwise behavior and performance should stay the same.

Add support for async generator injections
